config/routes.rb
Spree::Core::Engine.routes.draw do
    
  resources :suppliers
  resources :supplier_invoices
  resources :invoice_items

  namespace :admin do

    resources :suppliers do
      get 'feature'
      resources :taxons, :controller => "supplier_taxons" do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
          post :update_taxons
        end
      end
    end

    resources :products do
      resources :suppliers, :member => {:select => :post, :remove => :post}, :collection => {:available => :post, :selected => :get}
      member do
        get :publish
        get :unpublish
      end
    end
    resources :orders do
      resources :suppliers, :collection => {:line_items => :get}
    end

  end
  # Add your extension routes here
end

app/models/invoice_item.rb
class InvoiceItem < ActiveRecord::Base
    belongs_to :supplier_invoice
    belongs_to :line_item
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
      has_many :images, :as => :viewable, :order => :position, :dependent => :destroy
      accepts_nested_attributes_for :images
      belongs_to :user
      has_many :supplier_invoices
      has_and_belongs_to_many :taxons
      has_many :products
end

app/models/supplier_invoice.rb
class SupplierInvoice < ActiveRecord::Base
    belongs_to :supplier
    has_many :invoice_items
end

app/controllers/admin/supplier_taxons_controller.rb
class Admin::SupplierTaxonsController < Admin::BaseController
  include Railslove::Plugins::FindByParam::SingletonMethods
  helper "admin/taxons"

  respond_to :html, :json, :js

  def selected
    @supplier = load_supplier
    @taxons = @supplier.taxons
    @options = Taxon.all
    respond_with(:admin, @taxons)
  end

  def available
    @supplier = load_supplier
    @taxons = params[:q].blank? ? [] : Taxon.where('lower(name) LIKE ?', "%#{params[:q].mb_chars.downcase}%")
    @taxons.delete_if { |taxon| @supplier.taxons.include?(taxon) }
    respond_with(:admin, @taxons)
  end

  def remove
    @supplier = load_supplier
    @taxon = Taxon.find(params[:id])
    @supplier.taxons.delete(@taxon)
    @supplier.save
    @taxons = @supplier.taxons
    respond_with(@taxon) { |format| format.js { render_js_for_destroy } }
  end

  def select
    @supplier = load_supplier
    @taxon = Taxon.find(params[:id])
    @supplier.taxons << @taxon
    @supplier.save
    @taxons = @supplier.taxons
    respond_with(:admin, @taxons)
  end

  def batch_select
    @supplier = load_supplier
    @taxons = params[:taxon_ids].map{|id| Taxon.find(id)}.compact
    @supplier.taxons = @taxons
    @supplier.save
    redirect_to selected_admin_supplier_taxons_url(@supplier)
  end

  def update_taxons
    @supplier = Supplier.find params[:supplier_id]
    @supplier.taxons = []
    @supplier.taxons.push(Taxon.all.select{|t| params[t.name.to_s] })
    @supplier.save
    redirect_to :back, :notice => "Taxons successfully added"
  end

  private

  def load_supplier
    Supplier.find params[:supplier_id]
  end

end

app/controllers/admin/suppliers_controller.rb
class Admin::SuppliersController < Admin::BaseController
  resource_controller
  respond_to :html, :js

  def index
    if current_user.has_role?("admin")
      @suppliers = Supplier.all
    else
      @supplier = current_user.supplier
    end
  end

  def new
    @supplier = Supplier.new()
    @supplier.images.build
    @status = true
  end

  def create
    @supplier = Supplier.new(params[:supplier])
    if @supplier.save
      redirect_to admin_suppliers_path, :notice => "New supplier created"
    else
      render "new"
    end
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def edit
    @supplier = Supplier.find(params[:id])
    @supplier.images.build
  end

  def destroy
    @supplier = Supplier.find(params[:id])
    @supplier.destroy
    flash[:notice] = "Supplier Successfully deleted."
    respond_with(@product) do |format|
      format.html { redirect_to collection_url }
      format.js do
        render :update do |page|
          page.redirect_to collection_url
        end
      end
    end
  end

  def update
    @supplier = Supplier.find(params[:id])
    @status = false
    if @supplier.update_attributes(params[:supplier])
      redirect_to edit_admin_supplier_path, :notice => "Supplier updated"
    else
      render "edit"
    end
  end

  def feature
    @supplier = Supplier.find(params[:supplier_id])
    if @supplier.featured == true
      @supplier.featured = false
    else
      @supplier.featured = true
    end
    @supplier.save
    flash[:notice] = "change #{@supplier.title}'s feature status to #{@supplier.featured}"
    redirect_to admin_suppliers_path
  end

  def line_items
    @order = Order.find_by_number(params[:order_id])
  end

  def selected
    @supplier = @product.supplier
  end

  def available
    if params[:q].blank?
      @available_suppliers = []
    else
      @available_suppliers = Supplier.find(:all, :conditions => ['lower(name) LIKE ?', "%#{params[:q].downcase}%"])
    end
    @available_suppliers.delete_if { |supplier| @product.supplier == supplier }
    respond_to do |format|
      format.html
      format.js {render :layout => false}
    end

  end

  def remove
    @product.supplier = nil
    @product.save
    @supplier = @product.supplier
    render :layout => false
  end

  def select
    @supplier = Supplier.find_by_param!(params[:id])
    @product.supplier = @supplier
    @product.save
    @supplier = @product.supplier
    render :layout => false
  end


  update.response do |wants|
    wants.html { redirect_to collection_url }
  end

  update.after do
    Rails.cache.delete('suppliers')
  end

  create.response do |wants|
    wants.html { redirect_to collection_url }
  end

  create.after do
    Rails.cache.delete('suppliers')
  end

end

app/controllers/admin/vendor_overview_controller.rb
class Admin::VendorOverviewController < Spree::BaseController
  ssl_required

  helper :search
  helper 'admin/navigation'
  layout 'admin'

  before_filter :vendor

  def vendor 
    if !current_user.has_role?("vendor")
      unauthorized
    end
  end
  def index 
    
  end
end

app/controllers/invoice_items_controller.rb
class InvoiceItemsController < ApplicationController
end

app/controllers/supplier_invoices_controller.rb
class SupplierInvoicesController < ApplicationController
end

app/controllers/suppliers_controller.rb
class SuppliersController < Spree::BaseController
  helper :products
  respond_to :html

  def index
    @search = Supplier.search(params[:search])
    @suppliers = @search.all
    respond_with(@suppliers)
  end

  def show
    @supplier = Supplier.find(params[:id])
    @products = Product.find(:all, :conditions => { :supplier_id => @supplier.id , :deleted_at => nil })
  end
end

app/views/admin/orders/show.html.erb
<div class='toolbar order-links'>
  <%= hook :admin_order_show_buttons do %>
    <% if !current_user.has_role?("vendor") %>
       <%= button_link_to t("cancel"), fire_admin_order_url(@order.number, {:e => "cancel"}), :icon => 'delete', :confirm => t('are_you_sure') if @order.can_cancel? %>
      <%= button_link_to t("edit"), edit_admin_order_url(@order.number), :icon => 'edit' %>
    <% end %>
  <% end %>
</div>

<% render :partial => 'admin/shared/order_tabs_decide', :locals => {:current => "Order Details"} %>
<%= hook :admin_order_show_addresses do %>
  <% if @order.bill_address %>
    <div class='adr'>
      <h4><%= t("bill_address") %></h4>
      <%= render :partial => 'admin/shared/address', :locals => {:address => @order.bill_address} %>
    </div>
  <% end %>
  <% if @order.ship_address %>
    <div class='adr'>
      <h4><%= t("ship_address") %></h4>
      <%= render :partial => 'admin/shared/address', :locals => {:address => @order.ship_address} %>
    </div>
    <% end %>
  <hr />
<% end %>
<% if !current_user.has_role?("vendor") %>
  <%= hook :admin_order_show_details do %>
    <%= render :partial => 'admin/shared/order_details', :locals => {:order => @order} %>
  <% end %>

<% end %>
<h3><%= t("Supplier_Invoices") %></h3>
<%= render :partial => 'shared/supplier_invoices', :locals => {:order => @order} %>

app/views/admin/orders/user.html.erb
<%= render :partial => 'admin/shared/order_tabs_decide', :locals => {:current => "Customer Details"} %>
<%= csrf_meta_tag %>

<% if @order.cart? %>
  <div id="add-line-item" data-hook>
    <fieldset>
      <legend><%= t(:customer_search) %></legend>
      <%= label_tag :customer_search, t(:enter_at_least_five_letters) %>
      <%= text_field_tag :customer_search,  nil, :class => 'fullwidth title'  %>
    </fieldset>
  </div>
<% end %>

<%= render 'shared/error_messages', :target => @order %>

<%= form_for @order, :url => admin_order_url(@order), :html => { :method => :put} do |f| %>
  <%= f.hidden_field :number %>
  <%= render :partial => 'user_form', :locals => {:f => f} %>
<% end %>

app/views/admin/products/_form.html.erb
<div class="clearfix">
  <div class="left" data-hook="admin_product_form_left">
    <%= f.field_container :name do %>
      <%= f.label :name, t(:name) %> <span class="required">*</span><br />
      <%= f.text_field :name, :class => 'fullwidth title'  %>
      <%= f.error_message_on :name %>
    <% end %>

    <%= f.field_container :permalink do %>
      <%= f.label :permalink, t(:permalink) %> <span class="required">*</span><br />
      <%= f.text_field :permalink, :class => 'fullwidth title'  %>
      <%= f.error_message_on :permalink %>
    <% end %>

    <%= f.field_container :description do %>
      <%= f.label :description, t(:description)%><br />
      <%= f.text_area :description, {:cols => 60, :rows => 4, :class => 'fullwidth'} %>
      <%= f.error_message_on :description %>
    <% end %>
  </div>
  <div class="right" data-hook="admin_product_form_right">
      <%= f.field_container :price do %>
        <%= f.label :price, t(:master_price) %> <span class="required">*</span><br />
        <%= f.text_field :price, :value => number_with_precision(@product.price, :precision => 2)  %>
        <%= f.error_message_on :price %>
      <% end %>

      <%if Spree::Config[:show_price_inc_vat] %>
        <%= label_tag :price_includes_vat , I18n.t(:price_with_vat_included, :price => I18n.t(:price)) %><br />
        <%= text_field_tag :price_including_vat, product_price(@product, :show_vat_text => false), :size => 30 %>
        <%= javascript_tag do -%>
          var effective_tax_rate = <%= @product.effective_tax_rate %>;
        <% end -%>
      <% end %>

      <%= f.field_container :cost_price do %>
        <%= f.label :cost_price, t(:cost_price) %><br />
        <%= f.text_field :cost_price, :value => number_with_precision(@product.cost_price, :precision => 2) %>
      <%= f.error_message_on :cost_price %>
    <% end %>

    <p>
      <%= f.label :available_on, t(:available_on) %><br />
      <%= f.error_message_on :available_on %>
      <%= f.text_field :available_on, :class => 'datepicker' %>
    </p>

    <p>
      <%= render :partial => 'admin/products/suppliers_form', :locals => {:f => f} %>
    </p>


    <p>
      <%= f.label :sku, t(:sku) %><br />
      <%= f.text_field :sku, :size => 16 %>
    </p>
    <% unless @product.has_variants? %>
      <% if Spree::Config[:track_inventory_levels] %>
        <p>
          <%= f.label :on_hand, t(:on_hand) %><br />
          <%= f.text_field :on_hand, :size => 4 %>
        </p>
      <% end %>
      <ul id="shipping-specs">
        <li>
          <%= f.label :weight, t(:weight) %>
          <%= f.text_field :weight, :size => 4 %>
        </li>
        <li>
          <%= f.label :height, t(:height) %>
          <%= f.text_field :height, :size => 4 %>
        </li>
        <li>
          <%= f.label :width, t(:width) %>
          <%= f.text_field :width, :size => 4 %>
        </li>
        <li>
          <%= f.label :depth, t(:depth) %>
          <%= f.text_field :depth, :size => 4 %>
        </li>
      </ul>
    <% end %>
    <p>
      <%= f.label :shipping_category_id, t(:shipping_categories) %><br />
      <%= f.collection_select(:shipping_category_id, @shipping_categories, :id, :name, {:include_blank => true}, {'style' => 'width:200px'}) %>
      <%= f.error_message_on :shipping_category %>
    </p>

    <p>
      <%= f.label :tax_category_id, t(:tax_category) %><br />
      <%= f.collection_select(:tax_category_id, @tax_categories, :id, :name, {:include_blank => true}, {'style' => 'width:200px'}) %>
      <%= f.error_message_on :tax_category %>
    </p>
  </div>
</div>

<h2><%= t(:metadata) %></h2>
<div data-hook="admin_product_form_meta">
  <p>
    <%= f.label :meta_keywords, t(:meta_keywords) %><br />
    <%= f.text_field :meta_keywords, :class => 'fullwidth' %>
  </p>
  <p>
    <%= f.label :meta_description, t(:meta_description) %><br />
    <%= f.text_field :meta_description, :class => 'fullwidth' %>
  </p>
</div>


<div data-hook="admin_product_form_additional_fields">
  <% Variant.additional_fields.select{|af| af[:only].nil? || af[:only].include?(:product) }.each do |field| %>
    <%= render :partial => 'admin/shared/additional_field', :locals => {:field => field, :f => f} %>
  <% end %>
</div>

app/views/admin/products/_suppliers_form.html.erb
<p>
  <%= f.label :supplier_id, t("suppliers")%><br />
  <%= f.collection_select(:supplier_id, @suppliers, :id, :title, {:include_blank => true}) %>
</p>

app/views/admin/shared/_order_tabs_decide.html.erb
<% if current_user.has_role?("vendor") %>
  <%= render :partial => 'admin/shared/vendor_order_tabs', :locals => {:current => current}%>
<% else %>
  <%= render :partial => 'admin/shared/order_tabs', :locals => {:current => current} %>
<% end %>

app/views/admin/shared/_vendor_order_tabs.html.erb
<h1><%= t(:order) + " #{@order.number}" %></h1>

<% content_for :sidebar do %>
  <div id="order_tab_summary">
    <h3 id="order_number"><%= "#{t(:order)} ##{@order.number} " %></h3>
    <h5 id="order_status"><%= "#{t(:status)}: #{t("order_state.#{@order.state}")}" %></h5>
    <h5 id="order_total"><%= "#{t(:total)}: #{number_to_currency(@order.total)}" %></h5>
    <% if @order.completed? %>
      <h5 id="shipment_status"><%= "#{t(:shipment)}: #{t("shipment_states.#{@order.shipment_state}")}"  %></h5>
      <h5 id="payment_status"><%= "#{t(:payment)}: #{t("payment_states.#{@order.payment_state}")}" %></h5>
    <% end %>
    <br class="clear" />
  </div>
  <br class="clear" />

  <ul class="sidebar">
    <%= hook :admin_order_tabs, {:current => current} do %>
      <% unless @order.completed? %>
        <li<%== ' class="active"' if current == "Order Details" %>>
          <%= link_to t("order_details"), edit_admin_order_url(@order) %>
        </li>
        <li<%== ' class="active"' if current == "Customer Details" %>>
            <%= link_to t("customer_details"), user_admin_order_url(@order) %>
        </li>
      <% else %>
        <li<%== ' class="active"' if current == "Order Details" %>>
          <%= link_to t("order_details"), admin_order_url(@order) %>
        </li>
        <li<%== ' class="active"' if current == "Customer Details" %>>
          <%= link_to t("customer_details"), user_admin_order_url(@order) %>
        </li>
      <% end %>



    <% end %>
  </ul>

<% end %>

app/views/admin/supplier_taxons/_form.html.erb
<%= hook :admin_inside_taxon_form, {:f => f} do %>
  <%= f.field_container :name do %>
    <%= f.label :name, t("name") %> <span class="required">*</span><br />
    <%= error_message_on :taxon, :name, :class => 'fullwidth title'  %>
    <%= text_field :taxon, :name  %>
  <% end %>

  <%= f.field_container :permalink_part do %>
    <%= f.label :permalink_part, t("permalink") %><span class="required">*</span><br />
    <%= @taxon.permalink.split("/")[0...-1].join("/") + "/" %><%= text_field_tag :permalink_part, @permalink_part  %>
  <% end %>

  <%= f.field_container :icon do %>
    <%= f.label :icon, t('icon') %><br />
    <%= f.file_field :icon %>
  <% end %>

  <%= f.field_container :description do %>
    <%= f.label :description, t(:description) %><br />
    <%= f.text_area :description %>
  <% end %>

<% end %>

app/views/admin/supplier_taxons/_taxon_table.html.erb
<table class="index">
  <thead>
    <tr>
      <th><%= t("name") %></th>
      <th><%= t("path") %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% taxons.each do |taxon| %>
      <tr id="<%= dom_id(taxon)%>">
        <td><%= taxon.name %></td>
        <td><%= taxon_path taxon %></td>
        <td lass="actions">
          <%= link_to_delete taxon, :url => remove_admin_supplier_taxon_url(@supplier, taxon), :name => icon("delete") + ' ' + t("remove") %>
        </td>
      </tr>
    <% end %>
    <% if taxons.empty? %>
      <tr><td colspan="3"><%= t('none') %>.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/admin/supplier_taxons/available.js.erb
<script type="text/javascript">
  function displayRow(){
    var row = document.getElementById("captionRow");
    if (row.style.display == '') row.style.display = 'none';
    else row.style.display = '';
  }
</script>
<h4><%= t('available_taxons') %></h4>
<table class="index">
  <thead>
    <tr>
      <th><%= t("name") %></th>
      <th><%= t("path") %></th>
      <th><%= t("action") %></th>
    </tr>
  </thead>
  <tbody>
    <% @taxons.each do |taxon| %>
      <tr id="<%= dom_id(taxon, :sel) %>">
        <td><%= taxon.name %></td>
        <td><%= taxon_path taxon %></td>
        <td class="actions">
          <%= link_to icon('add') + ' ' + t("select"),
                            select_admin_supplier_taxon_path(@supplier, taxon),
                           :remote => true, :class => 'iconlink' %>
        </td>        
      </tr>
    <% end %>
    <% if @taxons.empty? %>
     <tr><td colspan="3"><%= t('no_match_found') %>.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/admin/supplier_taxons/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("taxon_edit")%></h1>

<%= form_for(:taxon, :url => admin_taxonomy_taxon_url(@taxonomy, @taxon), :html => { :method => :put, :multipart => true}) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>

  <p class="form-buttons">
    <%= button t("update") %> <%= t("or") %> <%= link_to t("cancel"), edit_admin_taxonomy_url(@taxonomy) %>
  </p>
<% end %>

app/views/admin/supplier_taxons/remove.html.erb
<%= render :partial => "taxon_table", :locals => {:taxons => @taxons} %>

app/views/admin/supplier_taxons/select.js.erb
$("#selected-taxons").html("<%= escape_javascript(render(:partial => "taxon_table", :locals => {:taxons => @taxons})) %>");
$("#<%= dom_id @taxon, :sel %>").hide();

app/views/admin/supplier_taxons/selected.html.erb
<h1>Editing Vendor</h1>

<%= render :partial => 'admin/suppliers/supplier_tabs', :locals => {:current => "Taxons"} %>

<%= form_tag({:controller => "supplier_taxons", :action => "update_taxons"}, :method => :post) do %>
  <h3>Category</h3>
  <ul>
    <% @options.each do |o| %>
      <%- if @supplier.taxons.select{|p| p.name == o.name}.present? %>
        <li><%= check_box_tag o.name, o.id, true %><%= label_tag o.name %></li>
      <% else %>
        <li><%= check_box_tag o.name, o.id %><%= label_tag o.name %></li>
      <% end %>
    <% end %>
  </ul>
  <%= submit_tag "Update" %>
<% end %>

app/views/admin/suppliers/_edit_hours_form.html.erb
<tr>
  <td><h4><%= day %></h4></td>
  <% outcome = @supplier.hours.first.send(day.downcase) %>
  <% if outcome == "Closed" || outcome == "Information Unavailable"  %>
    <% if outcome == "Information Unavailable" %>
      <%  outcome = "Unavailable" %>
    <% end %>
    <td><%= select_tag "#{day}_closed", options_for_select(@closed, outcome)  %></td>
  <% else %>
    <td><%= select_tag "#{day}_closed", options_for_select(@closed, "Open")  %></td>
  <% end %>
  <td>From: <%= select_tag "#{day}_begin", options_for_select(@hours, find_hours(outcome)[0]) %></td>
  <td><%= select_tag "#{day}_begin_mins", options_for_select(@minutes,find_minutes(outcome)[0]) %></td>
  <td><%= select_tag "#{day}_begin_type", options_for_select(@periods,find_periods(outcome)[0]) %>,   to</td>
  <td><%= select_tag "#{day}_end", options_for_select(@hours,find_hours(outcome)[1]) %><td>
  <td><%= select_tag "#{day}_end_mins", options_for_select(@minutes, find_minutes(outcome)[1]) %></td>
  <td><%= select_tag "#{day}_end_type", options_for_select(@periods,find_periods(outcome)[1]) %></td>
</tr>

app/views/admin/suppliers/_image_form.html.erb
<%= f.fields_for :images do |a| %>
  <%= a.label :image %>
  <%= a.file_field :attachment %>
<% end %>

<% if @supplier %>
  <% @supplier.images.each do |image| %>
    <%= image_tag(image) %>
  <% end %>
<% end %>

app/views/admin/suppliers/_supplier.html.erb
<h2>Supplier Info: <%= supplier.title %></h2>
<ul>
  <li><b>Company name:</b> <%= supplier.title %></li>
  <li><b>Vendor page:</b> <%= link_to supplier.title, supplier_path(supplier) %></li>
  <li><b>Description:</b> <%= supplier.notes %></li>
  <li><b>Phone:</b> <%= supplier.phone %></li>
  <li><b>Fax:</b><%= supplier.fax %></li>
  <li><b>Email:</b><%= supplier.email %></li>
  <li><b>Facebook:</b><%= supplier.facebook %></li>
  <li><b>Twitter:</b><%= supplier.twitter %></li>
  <li><b>Website:</b><%= supplier.website %></li>
</ul>
<h2>Proprietor Info</h2>
<ul>
  <li><b>Owner Name:</b><%= supplier.name %></li>
</ul>

<h2>Images</h2>
<% supplier.images.each do |image| %>
  <ul>
    <li><%= image_tag(image.attachment)%></li>
  </ul>
<% end %>

app/views/admin/suppliers/index.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>
<h1>
  <%= t("suppliers") %>
</h1>
<% if current_user.has_role?("admin") %>
  <div class='toolbar'>
    <ul class='actions'>
      <li id="new_product_link">
        <%= button_link_to "New Supplier", new_admin_supplier_path %>
      </li>
    </ul>
    <br class='clear' />
  </div>
  <table class="index" width="545">
    <thead>
      <tr>
        <th>
          <%= t("supplier_name") %>
        </th>
        <th>
          <%= t("notes") %>
        </th>
        <th>
          Actions
        </th>
        <th>
          Featured
        </th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr class="<%= cycle('even', 'odd') %>">
          <td>
            <%= link_to supplier.title, edit_admin_supplier_path(supplier) %>
          </td>
          <td>
            <%= truncate(supplier.notes, :length => 50) %>
          </td>
          <td class='actions'>
            <%= link_to_edit supplier, :class => 'edit' %>
            &nbsp;
            <%= link_to_delete supplier %>
          </td>
          <td>
            <% if supplier.featured %>
              <%= link_to "Yes", admin_supplier_feature_path(supplier) %>
            <% else %>
              <%= link_to "No", admin_supplier_feature_path(supplier) %>
            <% end %>
          </td>
      </tr><% end %>
    </tbody>
  </table>
<% else %>
  <table class="index" width="545">
    <thead>
      <tr>
        <th>
          <%= t("supplier_name") %>
        </th>
        <th>
          <%= t("notes") %>
        </th>
        <th>
          Actions
        </th>
        <th>
          Featured
        </th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td>
            <%= link_to @supplier.title, edit_admin_supplier_path(@supplier) %>
          </td>
          <td>
            <%= truncate(@supplier.notes, :length => 50) %>
          </td>
          <td class='actions'>
            <%= link_to_edit @supplier, :class => 'edit' %>
          </td>
          <td>
            <% if @supplier.featured %>
              Yes
            <% else %>
              No
            <% end %>
          </td>
      </tr>
    </tbody>
  </table>
<% end %>
<% if current_user.has_role?("admin") %>
  <%= link_to t("new_supplier"), new_object_url %>
<% end %>

app/views/admin/suppliers/remove.html.erb
<%= render :partial => "suppliers_table", :locals => {:supplier => @supplier} %>

app/views/admin/suppliers/select.html.erb
<%= render :partial => "suppliers_table", :locals => {:supplier => @supplier} %>

app/views/admin/suppliers/selected.html.erb
<%= render :partial => 'admin/suppliers/supplier_tabs', :locals => {:current => "Taxons"} %>

<div id="selected-taxons">
  <%= render :partial => "taxon_table", :locals => {:taxons => @taxons} %>
</div>

<%= form_tag('#') do %>
  <label><%= t('search') %>:</label>
  <input id="searchtext" size="25">
<% end %>

<%= javascript_tag do %>
  function search_for_taxons(){
    jQuery.ajax({
     data: {q: jQuery("#searchtext").val() }, 
     dataType: 'script',
     success: function(request){
       jQuery('#search_hits').html(request);
     },
     type: 'post',
     url: '<%= available_admin_supplier_taxons_url(@supplier) %>'
    });
  }

  jQuery("#searchtext").keypress(function (e) {
    if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
      search_for_taxons();

      return false;
    } else {
       return true;
    }
  });

  jQuery("#searchtext").delayedObserver(function() {
    search_for_taxons();
  }, 0.75);
<% end %>
<br/>
<div id="search_hits"></div>

app/views/admin/vendor_overview/index.html.erb
puts"HELLO"

app/views/suppliers/_supplier.html.erb
<div class="yui3-u-1-3">
  <div class="vendor">
    <% @products.each do |product|
      <%= link_to product.name, product_path(product) %>
    <% end %>
  </div>
</div>

app/views/suppliers/_supplier_list.erb
<li class="suppliers">
<div class="vendor-image">
  <%= link_to supplier.images.first, supplier_path(supplier) %>
</div>
<div class="article-content">
  <% if supplier.title %>
    <h4><%= link_to supplier.title, supplier_path(supplier) %> </h4>
  <% else %>
    <h4><%= link_to supplier.name, supplier_path(supplier) %> </h4>
  <% end %>
  </p>
</div>
</li>

app/views/suppliers/supplier_list.erb
<li>
<div class="vendor-image">
  <%= link_to supplier.images.first supplier_path(supplier)  %>
</div>
<div class="article-content">
  <h3><%= link_to supplier.title, supplier_path(supplier) %> </h3>
  <p class="supplier_about">
  <%= supplier.notes%> <br />
  <span class="phone"><%= supplier.phone %></span></p>
</div>
</li>